{% set name = "shogun" %}
{% set version = "6.0.0" %}
{% set sha256 = "413da26db7fb57aa36c2981bf92d23817c0a29f22051b331dbe5b86e46119748" %}
{% set blas_variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: shogun_{{ version }}.tar.gz
  url: https://github.com/shogun-toolbox/shogun/archive/shogun_{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  features:
    - blas_{{ blas_variant }}
  skip:
    - true  # [win]

requirements:
  build:
    - python
    - setuptools
    - toolchain
    - cmake
    - swig
    - numpy 1.8.*
    - shogun-cpp {{ version }}
    - arpack 3.5.*
    - bzip2 1.0.*
    - curl >=7.44.0,<8
    - eigen
    - glpk 4.61|4.62
    - hdf5 1.8.18|1.8.18.*
    - json-c 0.12|0.12.*
    - libxml2 2.9.*
    - lzo 2.*
    - openblas 0.2.19|0.2.19.*
    - protobuf 3.4.*
    - snappy 1.1.6|1.1.7
    - xz 5.2.*
    - zlib 1.2.8
  run:
    - python
    - numpy >=1.8
    - shogun-cpp {{ version }}
    - arpack 3.5.*
    - bzip2 1.0.*
    - curl >=7.44.0,<8
    - glpk 4.61|4.62
    - hdf5 1.8.18|1.8.18.*
    - json-c 0.12|0.12.*
    - libxml2 2.9.*
    - lzo 2.*
    - openblas 0.2.19|0.2.19.*
    - protobuf 3.4.*
    - snappy 1.1.6|1.1.7
    - xz 5.2.*
    - zlib 1.2.8

test:
  imports:
    - modshogun
  commands:
    - conda inspect linkages -p $PREFIX shogun  # [not win]
    - conda inspect objects -p $PREFIX shogun  # [win]

about:
  home: http://shogun.ml
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'Unified and efficient Machine Learning'
  description: |
    The Shogun Machine learning toolbox offers a wide range of efficient and
    unified Machine Learning methods.
  doc_url: http://shogun.ml/examples/latest/index.html
  dev_url: https://github.com/shogun-toolbox/shogun/wiki

extra:
  recipe-maintainers:
    - dougalsutherland
