travis:
  secure:
    BINSTAR_TOKEN: gAodoBw3ASYiHfuHJWWKSn4c1MVT02BwyxjEzt9SI+ABZ0Dosfz7Lc6Tgk6TJHRj57YZ2B0J1wBN6mh4s+2Cs0Q+A2HxU73uwsos38125pipMdv3xWuRkaxxQWZ5+K62dkKyWT1MSMGkAcWTg51eHCuW1vfXAbDJLqrDrTMbD9R5cZjtQHtZplKjONMv1tq+buLznGPqUXJ7M3k8wtQANc3hbJ046BJ8GVVA86en4WmbEZz/iP7CTHsGCAYOa9cpMlShxTcnJ3CnX1qvieGxMppuYJR+DaTbcIBlTs6F1LoywnKn2JUsq78MSfngjTHwhddpY1jvpDCIazlMN8uUvqmDzF+UyCZMa4tmtJG6wqBwFkWDf2wBtcF2YE3ve0IMAh6hSQdLilcqOyqCT/SlUe7+o705R4Dq3YXVhVYuxWNB1NGdsRsfbZbFAqA8z9Q+gNAqPg1rJXieVcPsP0oFfVd6TWWc8PfsMbUiPhTmY6yMTUaR0QMzESMpDnJIsaHJ0ON8iDxnIO1Yao0+ZppUaPKRwOWiSk+prL7XixtdzY1NEm/jU1P2SwadoA8E+0Tq1mJg3NWmvQsOcQMSxgeD+dLOehk3P7PjrBLnIq4bbyKRIzpSGyRSldr/Cvs5S38ZjtKaeEBgwcJEdoZzPNsSkrIE7/ZG0W+CeHOfKQ51n0o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
