travis:
  secure:
    BINSTAR_TOKEN: YdDqFw04Vg38lFP7/QmLuEXN/heUprxIb12xxJAm0Bm09Awk2Qv1f5RmcVASUV+Ect80fHkj2I+/F2QoSbmCL1pwLxC2NxjxfH6ixe1zIJ3oNd3dq3pDPTEhJHQeovKR2IlVxGgxEi+OMmFPCP3TpmIShk4aHxAdhNgv1+XV19xG3nDJofMNe924FKFATaJhlUt1Y8DQqiPbziFgTtTf4BniU5bwA+iv48g8Et7FGSSLcmjsHR2FQwQcwf6IbD8pdfsGAo1SPqCiVkKXYx5ceIpNLDT+Tl5PMK56ItxQLgWC3adNfAW/Xk5i+sPQ7cmUKkoimTZtJPDNhTT9ERMAKf6Pw8jdCnH98fm0pvN8ZAPUtAp+ZMgNCr3eo8i2KDmAG1CpncqYaLFGCimjWUeVrZ/E47NRtupXeJeVY0cyX9ijFL4FJmu5C2SW2gHB8p2g4NIiYvgJA0hh5cbjWxpLW2MvBunscmhZm9bvDOSp/njFfp4rp5sgF659/dWEPxwxnxUlRccE8NGaqlwPH895ZvsqjCFwvUtQK3KkZft0It8YqK4KSEOKcvJZxYBAmTTNKX/bjTqdi/XGDw7c7x7IBiP87aFfywHB8OYcT8EsJEQx8t9O/Ec7Jm1vUGTC1AFT1UjEFBM928WnK6P+jEUSDP6qFVpGKXF7ytm3nInS0N8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
